name: CI/CD on main branch

on:
  push:
    branches:
      - 'main'

jobs:
  exploration-games-deployment:
    uses: decentraland/platform-actions/.github/workflows/apps-docker-next.yml@main
    with:
      service-name: exploration-games
      image-name: exploration-games
      deployment-environment: dev
    secrets: inherit
